### ISSUE TITLE
Create new React Native project

### ISSUE THREAD

**Issue by elliottallmann** [KSU-SWE6733-Spring2023-Team3/development-project#8]
As a front-end developer, I want to have a new React Native project to build the user interface for an application. The new project should have a basic setup with necessary dependencies installed and other essential libraries. Additionally, I would like to have a preconfigured file structure for easier organization of the project and development process. 

## Acceptance Criteria
* A new React Native project is created with necessary dependencies installed 
* The project has a pre-configured file structure for easier organization of the development process
* The project is accessible to all members of the team

## Tasking
- [x] Set up a new React Native project with necessary configurations
- [x] Add necessary libraries and dependencies to the project
- [x] Ensure the project can be easily accessed and shared with other members of the development team
- [x] Set up a pre-configured file structure for the project including folders for assets, components, screens, and other necessary files
- [x] Create a README file for the project that outlines how to set it up and run it

**Comment by Siddhant422** [comment]
Hey elliottallmann, I wanted to work on this issue can you elaborate more about this issue.
I have few doubts regarding this issue what type of libraries and dependencies you want and do the folder of assets, component, screens should have any file included.
